FROM golang:alpine

WORKDIR /Go

COPY . .

RUN go mod init P1
RUN go get -u github.com/gorilla/mux
RUN go get -u github.com/gorilla/handlers
RUN go get -u github.com/rs/cors

EXPOSE 4000
CMD ["go","run","main.go"]